---
title: "assignment 4"
author: "Elli Linek"
date: "22 7 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r ass4_part A}
#game info data, should include: - game - teams - final score - score at break - date - time - city - stadium - attendance - game id

library(tidyverse)
library(lubridate)
library(pdftools)

dat <- pdf_text(pdf = "61_0706_uru-ned_fulltime.pdf")
#cat(dat)
#paste(dat)

dat <- dat[1]
dat <- str_split(dat, "Match Report\r\n.+\r\n", simplify = T)
dat <- dat[2]
#dat #checking back
dat <- str_split(dat,"Coach",simplify=T)[1]
#dat #checking back

game <- str_extract(dat,"[:alpha:]+[:blank:]-[:blank:][:alpha:]+")

team1 <- str_split(game," - ", simplify = T)[1]
team2 <- str_split(game," - ", simplify = T)[2]

dat <- str_split(dat,"[:alpha:]+[:blank:]-[:blank:][:alpha:]+[:blank:]+", simplify=T)[2]
score <- str_sub(dat,1,3)
score_45 <- str_extract(dat,"\\([:digit:]\\:[:digit:]\\)")
score_45 <- str_sub(score_45,2,4)
dat <- str_split(dat,"\\r\\n#[:blank:][:digit:]+[:blank:]*", simplify=T)[2]

date <- dmy(str_sub(dat,1,10))
year <- year(date)
dat <- str_split(dat,"[:digit:]{1,2}[:blank:][:alpha:]{3}[:blank:][:digit:]{4}[:blank:]*", simplify=T)[2]

time <- hm(str_sub(dat,1,5))
time
dat <- str_split(dat,"[:digit:]{2}\\:[:digit:]{2}[:blank:]*",simplify=T)[2]

city <- str_split(dat,"[:blank:]+\\/[:blank:]+",simplify=T)[1]

stadium <- str_split(dat,"[:blank:]+\\/[:blank:]+",simplify=T)[2]
dat <- str_split(dat,"[:blank:]+\\/[:blank:]+",simplify=T)[3]

att <- str_extract(dat,"Att\\.[:blank:][:digit:]+\\,[:digit:]+")
att <- str_extract(att,"[:digit:]+\\,[:digit:]+")
att <- str_c(str_split(att,",",simplify=T)[1],str_split(att,",",simplify=T)[2])
att <- as.numeric(att)

gameID <- str_c(game, score, year, sep="_")

#getting it into a data frame
gameINFO <- list(gameID, game, team1, team2, score, score_45, date, year, time, city, stadium, att)
gameINFO <- data.frame(gameINFO,stringsAsFactors = F)
vars <- c("gameID","Game","Team_1","Team_2","Score_at_End","Score_at_Halftime_Break","Date","Year","Time","City","Stadium_Name","Nr_of_Attendance")
colnames(gameINFO) <- vars
gameINFO

```


```{r ass4 part B}
#referee data. Should include: • name • role • country code

part1 <- str_split(dat,"\r\n",simplify = T)[2]
part2 <- str_split(dat,"\r\n",simplify = T)[3]
part3 <- str_split(dat,"\r\n",simplify = T)[4]
part4 <- str_split(dat,"\r\n",simplify = T)[5]

refereeINFO <- str_c(part1,part2,part3,part4)
refereeINFO <- data.frame(str_split(refereeINFO,"\\:|\\(|\\)",simplify = T),stringsAsFactors = F)
refereeINFO <- refereeINFO[,1:21]
refereeINFO <- str_replace_all(refereeINFO,"^[:blank:]{1,}","")
refereeINFO <- str_replace_all(refereeINFO,"$[:blank:]{1,}","")
refereeINFO

refereeINFO <- as.matrix(refereeINFO)
dim(refereeINFO) <- c(3,7)
refereeINFO <- t(refereeINFO)
refereeINFO <- data.frame(refereeINFO,stringsAsFactors = F)

colnames(refereeINFO) <- c("Role","Name","Country_Code")
refereeINFO$gameID <- gameID
refereeINFO
```


```{r ass4 part C}
#goals data. Should include: • scorer • country code • minute • game id

goalsINFO <- str_split(dat[1], "Goals Scored")[[1]][2]
goalsINFO <- str_split(goalsINFO, gameINFO$Team_1)[[1]][1]
goalsINFO <- str_remove_all(goalsINFO, "\n|\r|:|'|\"")
goalsINFO <- unlist(str_split(goalsINFO, " , "))
goalsINFO <- unlist(str_split(goalsINFO, "\\("))
goalsINFO <- unlist(str_split(goalsINFO, "\\) "))
goalsINFO

l <- length(goalsINFO)
ncol <- l/3
goalsINFO <- as.matrix(goalsINFO)
dim(goalsINFO) <- c(3,ncol)
goalsINFO <- t(goalsINFO)
goalsINFO <- data.frame(goalsINFO, stringsAsFactors = F)
colnames(goalsINFO) <- c("Scorer", "Country_Code", "Minute_in_Game")
goalsINFO$gameID <- gameID
goalsINFO

```




```{r ass4 part D}
#line up. Should include: • name • shirt number • team • game id 

dat <- str_split(dat,team2,simplify=T)[2]
dat <- str_replace(dat,"[:blank:]\\([:alpha:]{3}\\)\r\n","")
dat <- str_replace(dat,"Substitutes\\:[:blank:]+","")
dat <- str_replace(dat,"Substitutes:\r\n","")
dat <- str_split(dat,"\\[|\\]|\r\n",simplify=T)
dat <- dat[dat!=""]
dat <- dat[dat!="  "]
dat <- str_replace_all(dat,"^[:blank:]{1,}","")
dat <- str_replace_all(dat,"[:blank:]{1,}$","")
datl <- length(dat)
ncol <- datl/2
dat <- as.matrix(dat)
dim(dat) <- c(2,ncol)

datl <- length(dat)
ncol <- datl/2
dat <- as.matrix(dat)
dim(dat) <- c(2,ncol)
dat <- t(dat)
dat <- data.frame(dat, stringsAsFactors = F)
colnames(dat) <- c("Shirt_Number","Name")
dat$tempteam <- rep(c(1,2), nrow(dat)/2)
dat$team[dat$tempteam==1] <- team1
dat$team[dat$tempteam==2] <- team2
dat$tempteam <- NULL
dat$gameID <- gameID
dat$Shirt_Number <- as.numeric(dat$Shirt_Number)

lineUpINFO <- dat

Ass4_E.Linek <- list(gameINFO,refereeINFO,goalsINFO,lineUpINFO)
save(Ass4_E.Linek, file="Ass4_data_Elli_Linek.RData")

```

