
# Table Plots 
# Tennekes, M., Jonge, E. de, Daas, P.J.H. (2013) Visualizing and Inspecting Large Datasets with Tableplots, Journal of Data Science 11 (1), 43-58.

library(foreign)
library(tabplot)

data <- read.csv("/Users/richardtraunmuller/Dropbox/SwissData/data/02-t_pers_rs_harm_year2010/t_pers_rs_harm.csv")
data <- data[, c(7, 6, 9, 33, 36, 57)]

data$NATIONALITYCAT_HARM <- ifelse(data$NATIONALITYCAT_HARM==-9, NA, data$NATIONALITYCAT_HARM)
data$RELIGIOUSCOMMAGGII_HARM <- ifelse(data$RELIGIOUSCOMMAGGII_HARM==-9, NA, data$RELIGIOUSCOMMAGGII_HARM)
data$CURRACTIVITYSTATUSIII_HARM <- ifelse(data$CURRACTIVITYSTATUSIII_HARM==-9, NA, data$CURRACTIVITYSTATUSIII_HARM)

#data$SEX_HARM <- as.factor(data$SEX_HARM)
#data$NATIONALITYCAT_HARM <- as.factor(data$NATIONALITYCAT_HARM)
#data$RELIGIOUSCOMMAGGII_HARM <- as.factor(data$RELIGIOUSCOMMAGGII_HARM)
data$RES_CANTON_HARM <- as.factor(data$RES_CANTON_HARM)
#data$CURRACTIVITYSTATUSIII_HARM <- as.factor(data$CURRACTIVITYSTATUSIII_HARM)

data$SEX_HARM <- ifelse(data$SEX_HARM==1, "Male", "Female")
data$NATIONALITYCAT_HARM <- ifelse(data$NATIONALITYCAT_HARM==1, "Swiss", "Other")

data$RELIGIOUSCOMMAGGII_HARM <- ifelse(data$RELIGIOUSCOMMAGGII_HARM==1, "Catholic", data$RELIGIOUSCOMMAGGII_HARM)
data$RELIGIOUSCOMMAGGII_HARM <- ifelse(data$RELIGIOUSCOMMAGGII_HARM==2, "Reformed", data$RELIGIOUSCOMMAGGII_HARM)
data$RELIGIOUSCOMMAGGII_HARM <- ifelse(data$RELIGIOUSCOMMAGGII_HARM==3, "Other Christian", data$RELIGIOUSCOMMAGGII_HARM)
data$RELIGIOUSCOMMAGGII_HARM <- ifelse(data$RELIGIOUSCOMMAGGII_HARM==4, "Jewish", data$RELIGIOUSCOMMAGGII_HARM)
data$RELIGIOUSCOMMAGGII_HARM <- ifelse(data$RELIGIOUSCOMMAGGII_HARM==5, "Muslim", data$RELIGIOUSCOMMAGGII_HARM)
data$RELIGIOUSCOMMAGGII_HARM <- ifelse(data$RELIGIOUSCOMMAGGII_HARM==6, "Other", data$RELIGIOUSCOMMAGGII_HARM)
data$RELIGIOUSCOMMAGGII_HARM <- ifelse(data$RELIGIOUSCOMMAGGII_HARM==7, "None", data$RELIGIOUSCOMMAGGII_HARM)

data$CURRACTIVITYSTATUSIII_HARM <- ifelse(data$CURRACTIVITYSTATUSIII_HARM==1, "Full Time", data$CURRACTIVITYSTATUSIII_HARM)
data$CURRACTIVITYSTATUSIII_HARM <- ifelse(data$CURRACTIVITYSTATUSIII_HARM==2, "Part Time", data$CURRACTIVITYSTATUSIII_HARM)
data$CURRACTIVITYSTATUSIII_HARM <- ifelse(data$CURRACTIVITYSTATUSIII_HARM==3, "Part Time", data$CURRACTIVITYSTATUSIII_HARM)
data$CURRACTIVITYSTATUSIII_HARM <- ifelse(data$CURRACTIVITYSTATUSIII_HARM==4, "Part Time", data$CURRACTIVITYSTATUSIII_HARM)
data$CURRACTIVITYSTATUSIII_HARM <- ifelse(data$CURRACTIVITYSTATUSIII_HARM==5, "Unemployed", data$CURRACTIVITYSTATUSIII_HARM)
data$CURRACTIVITYSTATUSIII_HARM <- ifelse(data$CURRACTIVITYSTATUSIII_HARM==6, "In Education", data$CURRACTIVITYSTATUSIII_HARM)
data$CURRACTIVITYSTATUSIII_HARM <- ifelse(data$CURRACTIVITYSTATUSIII_HARM==7, "Home Work", data$CURRACTIVITYSTATUSIII_HARM)
data$CURRACTIVITYSTATUSIII_HARM <- ifelse(data$CURRACTIVITYSTATUSIII_HARM==8, "Retired", data$CURRACTIVITYSTATUSIII_HARM)
data$CURRACTIVITYSTATUSIII_HARM <- ifelse(data$CURRACTIVITYSTATUSIII_HARM==9, "Other", data$CURRACTIVITYSTATUSIII_HARM)


tableplot(data, sortCol=AGE_HARM)
tableplot(data, sortCol=RELIGIOUSCOMMAGGII_HARM, from=0, to=100, nBins=100)
tableplot(data, sortCol=RELIGIOUSCOMMAGGII_HARM, from=0, to=100, nBins=10)
tableplot(data, sortCol=RELIGIOUSCOMMAGGII_HARM, from=0, to=100, nBins=300)
tableplot(data, sortCol=RELIGIOUSCOMMAGGII_HARM, from=54, to=62, nBins=300)
tableplot(data, sortCol=CURRACTIVITYSTATUSIII_HARM, subset=RELIGIOUSCOMMAGGII_HARM=="Jewish", nBins=300)



ctableplot(data, sortCol=AGE_HARM, from=0, to=100, subset=RELIGIOUSCOMMAGGII_HARM=="Muslim")
